- menu_name: "Contact"

- name: "Email"
  url: "mailto:benprobison@gmail.com"
  title: "Email Ben Robison"

- name: "Resume"
  url: "/assets/docs/Ben_Robison_Resume.pdf"
  title: "Download Ben Robison's resume"
